FROM golang:1.15.2 AS builder
ARG GOOS=linux
ARG GOARCH=amd64
COPY . /work
RUN cd /work &&\
    CGO_ENABLED=0 GO111MODULE=on GOOS=${GOOS} GOARCH=${GOARCH} go build -a -o manager main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:latest
COPY --from=builder /work/manager .
USER 1000
ENTRYPOINT ["/manager"]
